language: java

before_install:
  - wget https://bitbucket.org/yildiz-engine-team/build-application-binaries/downloads/oraclejdk_linux-x64.zip
  - unzip oraclejdk_linux-x64.zip
  - wget https://bitbucket.org/yildiz-engine-team/build-application-binaries/downloads/apache-maven.zip
  - unzip -qq apache-maven.zip
  - ls
  - cd oraclejdk_linux-x64
  - ls
  - cd ..
  - export M2_HOME=$PWD/apache-maven
  - export JAVA_HOME=$PWD/oraclejdk_linux-x64
  - export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH
  - |
    if [ "${JDK_SYSTEM_CACERTS}" == '1' ]; then
      mv "${JAVA_HOME}/lib/security/cacerts" "${JAVA_HOME}/lib/security/cacerts.jdk"
      ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    fi

script:
  - mvn -V -B -s settings.xml test
install:
  - mvn -V -B -s settings.xml clean install
