version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\openjdk_windows-x64
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/yildiz-engine-team/build-application-binaries/downloads/apache-maven.zip', 'C:\maven-bin.zip')
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\")
      (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/yildiz-engine-team/build-application-binaries/downloads/openjdk_windows-x64.zip', 'C:\jdk.zip')
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\jdk.zip", "C:\")

  - cmd: SET PATH=C:\apache-maven\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -Dmaven.test.skip=true -s settings.xml
test_script:
  - mvn verify -B -s settings.xml